// ===== DEENTAG CORAN — JUZ DATA =====
// Informations sur chaque Juz (début et fin)

const JUZ_DATA = [
  { juz: 1, startSurah: 1, startName: { fr: "Al-Fatiha", en: "Al-Fatiha", es: "Al-Fatiha", de: "Al-Fatiha", it: "Al-Fatiha", nl: "Al-Fatiha", pt: "Al-Fatiha", tr: "Al-Fatiha" }, endSurah: 2, endName: { fr: "Al-Baqarah", en: "Al-Baqarah", es: "Al-Baqarah", de: "Al-Baqarah", it: "Al-Baqarah", nl: "Al-Baqarah", pt: "Al-Baqarah", tr: "Al-Baqarah" } },
  { juz: 2, startSurah: 2, startName: { fr: "Al-Baqarah", en: "Al-Baqarah", es: "Al-Baqarah", de: "Al-Baqarah", it: "Al-Baqarah", nl: "Al-Baqarah", pt: "Al-Baqarah", tr: "Al-Baqarah" }, endSurah: 2, endName: { fr: "Al-Baqarah", en: "Al-Baqarah", es: "Al-Baqarah", de: "Al-Baqarah", it: "Al-Baqarah", nl: "Al-Baqarah", pt: "Al-Baqarah", tr: "Al-Baqarah" } },
  { juz: 3, startSurah: 2, startName: { fr: "Al-Baqarah", en: "Al-Baqarah", es: "Al-Baqarah", de: "Al-Baqarah", it: "Al-Baqarah", nl: "Al-Baqarah", pt: "Al-Baqarah", tr: "Al-Baqarah" }, endSurah: 3, endName: { fr: "Al-Imran", en: "Al-Imran", es: "Al-Imran", de: "Al-Imran", it: "Al-Imran", nl: "Al-Imran", pt: "Al-Imran", tr: "Al-Imran" } },
  { juz: 4, startSurah: 3, startName: { fr: "Al-Imran", en: "Al-Imran", es: "Al-Imran", de: "Al-Imran", it: "Al-Imran", nl: "Al-Imran", pt: "Al-Imran", tr: "Al-Imran" }, endSurah: 4, endName: { fr: "An-Nisa", en: "An-Nisa", es: "An-Nisa", de: "An-Nisa", it: "An-Nisa", nl: "An-Nisa", pt: "An-Nisa", tr: "An-Nisa" } },
  { juz: 5, startSurah: 4, startName: { fr: "An-Nisa", en: "An-Nisa", es: "An-Nisa", de: "An-Nisa", it: "An-Nisa", nl: "An-Nisa", pt: "An-Nisa", tr: "An-Nisa" }, endSurah: 4, endName: { fr: "An-Nisa", en: "An-Nisa", es: "An-Nisa", de: "An-Nisa", it: "An-Nisa", nl: "An-Nisa", pt: "An-Nisa", tr: "An-Nisa" } },
  { juz: 6, startSurah: 4, startName: { fr: "An-Nisa", en: "An-Nisa", es: "An-Nisa", de: "An-Nisa", it: "An-Nisa", nl: "An-Nisa", pt: "An-Nisa", tr: "An-Nisa" }, endSurah: 5, endName: { fr: "Al-Ma'idah", en: "Al-Ma'idah", es: "Al-Ma'idah", de: "Al-Ma'idah", it: "Al-Ma'idah", nl: "Al-Ma'idah", pt: "Al-Ma'idah", tr: "Al-Ma'idah" } },
  { juz: 7, startSurah: 5, startName: { fr: "Al-Ma'idah", en: "Al-Ma'idah", es: "Al-Ma'idah", de: "Al-Ma'idah", it: "Al-Ma'idah", nl: "Al-Ma'idah", pt: "Al-Ma'idah", tr: "Al-Ma'idah" }, endSurah: 6, endName: { fr: "Al-An'am", en: "Al-An'am", es: "Al-An'am", de: "Al-An'am", it: "Al-An'am", nl: "Al-An'am", pt: "Al-An'am", tr: "Al-An'am" } },
  { juz: 8, startSurah: 6, startName: { fr: "Al-An'am", en: "Al-An'am", es: "Al-An'am", de: "Al-An'am", it: "Al-An'am", nl: "Al-An'am", pt: "Al-An'am", tr: "Al-An'am" }, endSurah: 7, endName: { fr: "Al-A'raf", en: "Al-A'raf", es: "Al-A'raf", de: "Al-A'raf", it: "Al-A'raf", nl: "Al-A'raf", pt: "Al-A'raf", tr: "Al-A'raf" } },
  { juz: 9, startSurah: 7, startName: { fr: "Al-A'raf", en: "Al-A'raf", es: "Al-A'raf", de: "Al-A'raf", it: "Al-A'raf", nl: "Al-A'raf", pt: "Al-A'raf", tr: "Al-A'raf" }, endSurah: 8, endName: { fr: "Al-Anfal", en: "Al-Anfal", es: "Al-Anfal", de: "Al-Anfal", it: "Al-Anfal", nl: "Al-Anfal", pt: "Al-Anfal", tr: "Al-Anfal" } },
  { juz: 10, startSurah: 8, startName: { fr: "Al-Anfal", en: "Al-Anfal", es: "Al-Anfal", de: "Al-Anfal", it: "Al-Anfal", nl: "Al-Anfal", pt: "Al-Anfal", tr: "Al-Anfal" }, endSurah: 9, endName: { fr: "At-Taubah", en: "At-Taubah", es: "At-Taubah", de: "At-Taubah", it: "At-Taubah", nl: "At-Taubah", pt: "At-Taubah", tr: "At-Taubah" } },
  { juz: 11, startSurah: 9, startName: { fr: "At-Taubah", en: "At-Taubah", es: "At-Taubah", de: "At-Taubah", it: "At-Taubah", nl: "At-Taubah", pt: "At-Taubah", tr: "At-Taubah" }, endSurah: 11, endName: { fr: "Hud", en: "Hud", es: "Hud", de: "Hud", it: "Hud", nl: "Hud", pt: "Hud", tr: "Hud" } },
  { juz: 12, startSurah: 11, startName: { fr: "Hud", en: "Hud", es: "Hud", de: "Hud", it: "Hud", nl: "Hud", pt: "Hud", tr: "Hud" }, endSurah: 12, endName: { fr: "Yusuf", en: "Yusuf", es: "Yusuf", de: "Yusuf", it: "Yusuf", nl: "Yusuf", pt: "Yusuf", tr: "Yusuf" } },
  { juz: 13, startSurah: 12, startName: { fr: "Yusuf", en: "Yusuf", es: "Yusuf", de: "Yusuf", it: "Yusuf", nl: "Yusuf", pt: "Yusuf", tr: "Yusuf" }, endSurah: 14, endName: { fr: "Ibrahim", en: "Ibrahim", es: "Ibrahim", de: "Ibrahim", it: "Ibrahim", nl: "Ibrahim", pt: "Ibrahim", tr: "Ibrahim" } },
  { juz: 14, startSurah: 15, startName: { fr: "Al-Hijr", en: "Al-Hijr", es: "Al-Hijr", de: "Al-Hijr", it: "Al-Hijr", nl: "Al-Hijr", pt: "Al-Hijr", tr: "Al-Hijr" }, endSurah: 16, endName: { fr: "An-Nahl", en: "An-Nahl", es: "An-Nahl", de: "An-Nahl", it: "An-Nahl", nl: "An-Nahl", pt: "An-Nahl", tr: "An-Nahl" } },
  { juz: 15, startSurah: 17, startName: { fr: "Al-Isra", en: "Al-Isra", es: "Al-Isra", de: "Al-Isra", it: "Al-Isra", nl: "Al-Isra", pt: "Al-Isra", tr: "Al-Isra" }, endSurah: 18, endName: { fr: "Al-Kahf", en: "Al-Kahf", es: "Al-Kahf", de: "Al-Kahf", it: "Al-Kahf", nl: "Al-Kahf", pt: "Al-Kahf", tr: "Al-Kahf" } },
  { juz: 16, startSurah: 18, startName: { fr: "Al-Kahf", en: "Al-Kahf", es: "Al-Kahf", de: "Al-Kahf", it: "Al-Kahf", nl: "Al-Kahf", pt: "Al-Kahf", tr: "Al-Kahf" }, endSurah: 20, endName: { fr: "Ta-Ha", en: "Ta-Ha", es: "Ta-Ha", de: "Ta-Ha", it: "Ta-Ha", nl: "Ta-Ha", pt: "Ta-Ha", tr: "Ta-Ha" } },
  { juz: 17, startSurah: 21, startName: { fr: "Al-Anbiya", en: "Al-Anbiya", es: "Al-Anbiya", de: "Al-Anbiya", it: "Al-Anbiya", nl: "Al-Anbiya", pt: "Al-Anbiya", tr: "Al-Anbiya" }, endSurah: 22, endName: { fr: "Al-Hajj", en: "Al-Hajj", es: "Al-Hajj", de: "Al-Hajj", it: "Al-Hajj", nl: "Al-Hajj", pt: "Al-Hajj", tr: "Al-Hajj" } },
  { juz: 18, startSurah: 23, startName: { fr: "Al-Muminun", en: "Al-Muminun", es: "Al-Muminun", de: "Al-Muminun", it: "Al-Muminun", nl: "Al-Muminun", pt: "Al-Muminun", tr: "Al-Muminun" }, endSurah: 25, endName: { fr: "Al-Furqan", en: "Al-Furqan", es: "Al-Furqan", de: "Al-Furqan", it: "Al-Furqan", nl: "Al-Furqan", pt: "Al-Furqan", tr: "Al-Furqan" } },
  { juz: 19, startSurah: 25, startName: { fr: "Al-Furqan", en: "Al-Furqan", es: "Al-Furqan", de: "Al-Furqan", it: "Al-Furqan", nl: "Al-Furqan", pt: "Al-Furqan", tr: "Al-Furqan" }, endSurah: 27, endName: { fr: "An-Naml", en: "An-Naml", es: "An-Naml", de: "An-Naml", it: "An-Naml", nl: "An-Naml", pt: "An-Naml", tr: "An-Naml" } },
  { juz: 20, startSurah: 27, startName: { fr: "An-Naml", en: "An-Naml", es: "An-Naml", de: "An-Naml", it: "An-Naml", nl: "An-Naml", pt: "An-Naml", tr: "An-Naml" }, endSurah: 29, endName: { fr: "Al-Ankabut", en: "Al-Ankabut", es: "Al-Ankabut", de: "Al-Ankabut", it: "Al-Ankabut", nl: "Al-Ankabut", pt: "Al-Ankabut", tr: "Al-Ankabut" } },
  { juz: 21, startSurah: 29, startName: { fr: "Al-Ankabut", en: "Al-Ankabut", es: "Al-Ankabut", de: "Al-Ankabut", it: "Al-Ankabut", nl: "Al-Ankabut", pt: "Al-Ankabut", tr: "Al-Ankabut" }, endSurah: 33, endName: { fr: "Al-Ahzab", en: "Al-Ahzab", es: "Al-Ahzab", de: "Al-Ahzab", it: "Al-Ahzab", nl: "Al-Ahzab", pt: "Al-Ahzab", tr: "Al-Ahzab" } },
  { juz: 22, startSurah: 33, startName: { fr: "Al-Ahzab", en: "Al-Ahzab", es: "Al-Ahzab", de: "Al-Ahzab", it: "Al-Ahzab", nl: "Al-Ahzab", pt: "Al-Ahzab", tr: "Al-Ahzab" }, endSurah: 36, endName: { fr: "Ya-Sin", en: "Ya-Sin", es: "Ya-Sin", de: "Ya-Sin", it: "Ya-Sin", nl: "Ya-Sin", pt: "Ya-Sin", tr: "Ya-Sin" } },
  { juz: 23, startSurah: 36, startName: { fr: "Ya-Sin", en: "Ya-Sin", es: "Ya-Sin", de: "Ya-Sin", it: "Ya-Sin", nl: "Ya-Sin", pt: "Ya-Sin", tr: "Ya-Sin" }, endSurah: 39, endName: { fr: "Az-Zumar", en: "Az-Zumar", es: "Az-Zumar", de: "Az-Zumar", it: "Az-Zumar", nl: "Az-Zumar", pt: "Az-Zumar", tr: "Az-Zumar" } },
  { juz: 24, startSurah: 39, startName: { fr: "Az-Zumar", en: "Az-Zumar", es: "Az-Zumar", de: "Az-Zumar", it: "Az-Zumar", nl: "Az-Zumar", pt: "Az-Zumar", tr: "Az-Zumar" }, endSurah: 41, endName: { fr: "Fussilat", en: "Fussilat", es: "Fussilat", de: "Fussilat", it: "Fussilat", nl: "Fussilat", pt: "Fussilat", tr: "Fussilat" } },
  { juz: 25, startSurah: 41, startName: { fr: "Fussilat", en: "Fussilat", es: "Fussilat", de: "Fussilat", it: "Fussilat", nl: "Fussilat", pt: "Fussilat", tr: "Fussilat" }, endSurah: 45, endName: { fr: "Al-Jathiya", en: "Al-Jathiya", es: "Al-Jathiya", de: "Al-Jathiya", it: "Al-Jathiya", nl: "Al-Jathiya", pt: "Al-Jathiya", tr: "Al-Jathiya" } },
  { juz: 26, startSurah: 46, startName: { fr: "Al-Ahqaf", en: "Al-Ahqaf", es: "Al-Ahqaf", de: "Al-Ahqaf", it: "Al-Ahqaf", nl: "Al-Ahqaf", pt: "Al-Ahqaf", tr: "Al-Ahqaf" }, endSurah: 51, endName: { fr: "Ad-Dhariyat", en: "Ad-Dhariyat", es: "Ad-Dhariyat", de: "Ad-Dhariyat", it: "Ad-Dhariyat", nl: "Ad-Dhariyat", pt: "Ad-Dhariyat", tr: "Ad-Dhariyat" } },
  { juz: 27, startSurah: 51, startName: { fr: "Ad-Dhariyat", en: "Ad-Dhariyat", es: "Ad-Dhariyat", de: "Ad-Dhariyat", it: "Ad-Dhariyat", nl: "Ad-Dhariyat", pt: "Ad-Dhariyat", tr: "Ad-Dhariyat" }, endSurah: 57, endName: { fr: "Al-Hadid", en: "Al-Hadid", es: "Al-Hadid", de: "Al-Hadid", it: "Al-Hadid", nl: "Al-Hadid", pt: "Al-Hadid", tr: "Al-Hadid" } },
  { juz: 28, startSurah: 58, startName: { fr: "Al-Mujadilah", en: "Al-Mujadilah", es: "Al-Mujadilah", de: "Al-Mujadilah", it: "Al-Mujadilah", nl: "Al-Mujadilah", pt: "Al-Mujadilah", tr: "Al-Mujadilah" }, endSurah: 66, endName: { fr: "At-Tahrim", en: "At-Tahrim", es: "At-Tahrim", de: "At-Tahrim", it: "At-Tahrim", nl: "At-Tahrim", pt: "At-Tahrim", tr: "At-Tahrim" } },
  { juz: 29, startSurah: 67, startName: { fr: "Al-Mulk", en: "Al-Mulk", es: "Al-Mulk", de: "Al-Mulk", it: "Al-Mulk", nl: "Al-Mulk", pt: "Al-Mulk", tr: "Al-Mulk" }, endSurah: 77, endName: { fr: "Al-Mursalat", en: "Al-Mursalat", es: "Al-Mursalat", de: "Al-Mursalat", it: "Al-Mursalat", nl: "Al-Mursalat", pt: "Al-Mursalat", tr: "Al-Mursalat" } },
  { juz: 30, startSurah: 78, startName: { fr: "An-Naba", en: "An-Naba", es: "An-Naba", de: "An-Naba", it: "An-Naba", nl: "An-Naba", pt: "An-Naba", tr: "An-Naba" }, endSurah: 114, endName: { fr: "An-Nas", en: "An-Nas", es: "An-Nas", de: "An-Nas", it: "An-Nas", nl: "An-Nas", pt: "An-Nas", tr: "An-Nas" } }
];

// Fonction pour obtenir les infos d'un Juz
function getJuzInfo(juzNum, lang = 'fr') {
  const juz = JUZ_DATA.find(j => j.juz === juzNum);
  if (!juz) return null;
  
  return {
    juz: juz.juz,
    start: `${juz.startSurah}. ${juz.startName[lang] || juz.startName['en']}`,
    end: `${juz.endSurah}. ${juz.endName[lang] || juz.endName['en']}`
  };
}
